### ISSUE TITLE
The appendix file of the paper

### ISSUE THREAD

**Issue by a962097364** [chenshaoyu1995/InstantReality#1]
Hello! Thanks for your special work!

I want to download your paper's appendix file from IEEE, but I noticed that under the IEEE link to the paper there is no way to download the appendix file. How can I download the appendix file of the paper? 

Thank you.

**Comment by chenshaoyu1995** [comment]
Hi,

You can find the appendix at the end of [the pdf on arxiv](https://arxiv.org/pdf/2201.03484.pdf).

**Comment by a962097364** [comment]
That's helps me a lot, thanks.
